<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    
    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-sm-12">'.$block->toHtml().'</div></div>';
        }
    }
?>
<section id="contact">
	<div class="row">
		<div class="col-sm-12 block-content"><?php echo $this->getChildHtml('contactForm')?></div>
	<!--	<div class="col-sm-12 block-content contact-info">
			<div class="contacts-title"><?php echo __('Contact') ?> <b><?php echo __('Details') ?></b></div>
			<?php echo $_infoblock; ?>
		</div> -->
	</div>
</section>